function exportNeighborKappaResults(artifactDirectory,outputDirectory)
% Export compact offline evidence without copying retained continuous bases.
arguments
    artifactDirectory (1,1) string
    outputDirectory (1,1) string
end
if ~isfolder(outputDirectory), mkdir(outputDirectory); end
loaded = load(fullfile(artifactDirectory,'summary.mat'),'records','configuration','summary');
records = loaded.records; configuration = loaded.configuration;
rows = struct([]);
for i = 1:numel(records)
    r = records(i);
    for j = 1:numel(configuration.bands)
        row = struct('caseId',r.caseId,'profile',r.profile,'surface',r.surface,'sourceKappa',r.sourceKappa,'requestedKappa',r.requestedKappa,'relativeOffset',r.relativeOffset,'band',configuration.bands(j), ...
            'referenceOrder',r.referenceOrder,'referenceQualifiedExperimental',r.referenceQualifiedExperimental,'referenceEigenChange',r.referenceComparison.eigenvalueError(j),'referenceSubspaceChange',r.referenceComparison.subspaceError(j), ...
            'referenceEquationError',r.referenceResidual.equationError,'referenceBoundaryError',r.referenceResidual.boundaryError,'cutoffRelativeGap',r.referenceComparison.cutoffRelativeGap(j), ...
            'minimumInternalRelativeGap',r.referenceComparison.minimumRelativeGap,'minimumParticipationFraction',min(r.referenceResidual.participationFraction(1:configuration.bands(j))), ...
            'maximumUpperQuarterFraction',max(r.referenceResidual.upperQuarterFraction(1:configuration.bands(j))), ...
            'baselineEigenError',r.baselineComparison.eigenvalueError(j),'baselineFrequencyError',r.baselineComparison.frequencyError(j),'baselineSubspaceError',r.baselineComparison.subspaceError(j), ...
            'warmFlag',r.warmCost.flag,'coldFlag',r.coldCost.flag,'warmOperatorApplications',r.warmCost.operatorApplications,'coldOperatorApplications',r.coldCost.operatorApplications, ...
            'warmToFullEigenError',r.warmToFull.eigenvalueError(j),'warmToFullSubspaceError',r.warmToFull.subspaceError(j),'warmToReferenceEigenError',r.warmComparison.eigenvalueError(j), ...
            'warmToReferenceSubspaceError',r.warmComparison.subspaceError(j),'warmToReferenceIndividualH1Error',r.warmComparison.individualH1Error(j), ...
            'approximateEigenError',r.approximateComparison.eigenvalueError(j),'approximateFrequencyError',r.approximateComparison.frequencyError(j),'approximateSubspaceError',r.approximateComparison.subspaceError(j), ...
            'approximateIndividualH1Error',r.approximateComparison.individualH1Error(j),'approximateFError',r.approximateComparison.FError(j), ...
            'approximateEquationError',r.approximateResidual.equationError,'approximateBoundaryError',r.approximateResidual.boundaryError, ...
            'warmMatchesFull',r.warmMatchesFull,'fallbackRequired',r.fallbackRequired,'fullSolveSeconds',r.fullSolveSeconds,'warmRawSeconds',r.warmCost.totalSeconds,'coldRawSeconds',r.coldCost.totalSeconds, ...
            'warmFactorizationSeconds',r.warmCost.factorizationSeconds,'warmEigensolveSeconds',r.warmCost.eigensolveSeconds,'warmFinalizationSeconds',r.warmCost.finalizationSeconds, ...
            'requestedAssemblySeconds',r.requestedAssemblySeconds,'requestedSelectionSeconds',r.requestedSelectionSeconds,'warmValidationSeconds',r.warmValidationSeconds, ...
            'referenceSolveSeconds',r.referenceSolveSeconds,'referenceValidationSeconds',r.referenceValidationSeconds,'baselineValidationSeconds',r.baselineValidationSeconds, ...
            'neighborAcquisitionSeconds',r.neighborAcquisitionSeconds,'warmWithValidationAndFallbackSeconds',r.warmTotalWithFallbackSeconds,'warmWithAllReferenceSeconds',r.validatedWithReferenceSeconds, ...
            'analyticAvailable',r.analyticControl.available,'analyticEigenError',NaN,'analyticSubspaceError',NaN,'productionQualification',false);
        if r.analyticControl.available
            row.analyticEigenError = r.analyticControl.comparison.eigenvalueError(j);
            row.analyticSubspaceError = r.analyticControl.comparison.subspaceError(j);
        end
        if isempty(rows), rows = row; else, rows(end+1) = row; end %#ok<AGROW>
    end
end
writetable(struct2table(rows),fullfile(outputDirectory,'measurements.csv'));
writetable(configuration.cases,fullfile(outputDirectory,'case-matrix.csv'));
writeJSON(fullfile(outputDirectory,'configuration.json'),rmfield(configuration,'cases'));
writeJSON(fullfile(outputDirectory,'summary.json'),loaded.summary);
end
function writeJSON(path,value)
fid = fopen(path,'w'); cleanup = onCleanup(@() fclose(fid));
fprintf(fid,'%s\n',jsonencode(value,PrettyPrint=true));
end
