function [denseSummary,partialSummary,correctnessResults,partialResults] = refreshWaveEigensolverStudySummaries(options)
% Run the corrected eigensolver studies and refresh their summary CSV files.
arguments
    options.outputDirectory (1,1) string = string(fileparts(mfilename("fullpath")))
    options.repetitions (1,1) double {mustBeInteger,mustBePositive} = 15
end

correctnessResults = runWaveEigensolverCorrectnessStudy();
partialResults = measurePartialWaveEigensolver(repetitions=options.repetitions);
denseSummary = summarizeDenseResults(correctnessResults);
partialSummary = summarizePartialResults(partialResults);
writetable(denseSummary,fullfile(options.outputDirectory,"dense-candidate-summary.csv"));
writetable(partialSummary,fullfile(options.outputDirectory,"partial-timing-summary.csv"));
end

function summary = summarizeDenseResults(results)
candidates = unique(string(results.candidate));
rows = cell(numel(candidates),17);
for iCandidate = 1:numel(candidates)
    candidate = candidates(iCandidate);
    subset = results(string(results.candidate) == candidate,:);
    rows(iCandidate,:) = {candidate,height(subset), ...
        mean(subset.generalizedPreparationSeconds),mean(subset.generalizedSolveSeconds), ...
        mean(subset.generalizedReconstructionSeconds),mean(subset.generalizedTotalSeconds), ...
        mean(subset.candidatePreparationSeconds),mean(subset.candidateSolveSeconds), ...
        mean(subset.candidateReconstructionSeconds),mean(subset.candidateTotalSeconds), ...
        mean(subset.candidateTotalOverGeneralizedTotal),max(subset.candidateTotalOverGeneralizedTotal), ...
        max(subset.maximumPencilResidual),max(subset.maximumRelativeHError), ...
        max(subset.relativeGError),max(subset.relativeFError),nnz(~subset.labelsEqual)};
end
summary = cell2table(rows,VariableNames=["candidate","caseCount","meanGeneralizedPreparationSeconds", ...
    "meanGeneralizedSolveSeconds","meanGeneralizedReconstructionSeconds","meanGeneralizedTotalSeconds", ...
    "meanCandidatePreparationSeconds","meanCandidateSolveSeconds","meanCandidateReconstructionSeconds", ...
    "meanCandidateTotalSeconds","meanCandidateTotalOverGeneralizedTotal", ...
    "maximumCandidateTotalOverGeneralizedTotal","maximumPencilResidual","maximumRelativeHError", ...
    "maximumRelativeGError","maximumRelativeFError","labelMismatches"]);
end

function summary = summarizePartialResults(results)
resolutions = unique(results.nEVP);
modeCounts = unique(results.requestedModes);
rows = cell(numel(resolutions)*numel(modeCounts),17);
iRow = 0;
for nEVP = resolutions.'
    for nModes = modeCounts.'
        iRow = iRow+1;
        subset = results(results.nEVP == nEVP & results.requestedModes == nModes,:);
        rows(iRow,:) = {nEVP,nModes,height(subset), ...
            mean(subset.fullPreparationMedianSeconds),mean(subset.fullSolveMedianSeconds), ...
            mean(subset.fullReconstructionMedianSeconds),mean(subset.fullTotalMedianSeconds), ...
            mean(subset.partialPreparationMedianSeconds),mean(subset.partialReductionMedianSeconds), ...
            mean(subset.partialSolveMedianSeconds),mean(subset.partialReconstructionMedianSeconds), ...
            mean(subset.partialTotalMedianSeconds),mean(subset.partialTotalOverFullTotal), ...
            max(subset.partialTotalOverFullTotal),max(subset.maximumRelativeEigenvalueError), ...
            max(subset.maximumPencilResidual),nnz(subset.flag ~= 0)};
    end
end
summary = cell2table(rows,VariableNames=["nEVP","requestedModes","caseCount", ...
    "meanFullPreparationMedianSeconds","meanFullSolveMedianSeconds", ...
    "meanFullReconstructionMedianSeconds","meanFullTotalMedianSeconds", ...
    "meanPartialPreparationMedianSeconds","meanPartialReductionMedianSeconds", ...
    "meanPartialSolveMedianSeconds","meanPartialReconstructionMedianSeconds", ...
    "meanPartialTotalMedianSeconds","meanPartialTotalOverFullTotal", ...
    "maximumPartialTotalOverFullTotal","maximumRelativeEigenvalueError", ...
    "maximumPencilResidual","nonzeroFlags"]);
end
