function z = quadraturePoints(self, options)
% Return a full-depth grid generated by the next selected mode.
%
% For the first $$N$$ retained scalar modes, `quadraturePoints` uses the
% next selected mode $$u_{N+1}$$ and returns
%
% $$
% \mathbf{z}_q=\{z_b\}\cup
% \left\{z\in(z_b,z_s):u_{N+1}(z)=0\right\}\cup\{z_s\}.
% $$
%
% Here `nModes=N` counts the same retained column prefix used by
% `discreteTransform`; it is not interpreted as a physical `modeNumber`.
% If the generating column was not retained, the stored solver and EVP are
% used to solve for one additional mode without changing this basis set.
% The returned grid is a canonical candidate. Its quadrature weights and
% Gram accuracy should still be assessed with `quadratureWeightsForPoints`.
%
% ```matlab
% z = basisSet.quadraturePoints(nModes=8);
% weights = basisSet.quadratureWeightsForPoints(z=z,nModes=8);
% transform = basisSet.discreteTransform(z=z,weights=weights,nModes=8);
% ```
%
% - Topic: Build discrete transforms
% - Declaration: z = quadraturePoints(basisSet,options)
% - Parameter options.nModes: number of leading retained modes represented by the grid
% - Returns z: increasing full-depth mode-root grid
arguments
    self IMBasisSet
    options.nModes (1,1) double {mustBeInteger, mustBePositive} = size(self.nativeModes,2)
end

nModes = options.nModes;
nRetained = size(self.nativeModes,2);
if nModes > nRetained
    error("IMBasisSet:InvalidQuadratureModeCount", ...
        "The basis set contains %d retained modes, but nModes=%d was requested.", nRetained, nModes);
end

if nModes < nRetained
    generatingMode = self.nativeModes(:,nModes+1);
else
    try
        auxiliaryBasis = self.solver.solveEVP(self.evp,nModes=nModes+1);
    catch exception
        wrapped = MException("IMBasisSet:AuxiliaryModeUnavailable", ...
            "The solver could not obtain the auxiliary mode required for a %d-mode quadrature grid.", nModes);
        wrapped = addCause(wrapped,exception);
        throwAsCaller(wrapped)
    end
    if size(auxiliaryBasis.nativeModes,2) < nModes+1
        error("IMBasisSet:AuxiliaryModeUnavailable", ...
            "The solver returned %d selected modes, but %d are required to generate this grid. Increase the solver resolution.", ...
            size(auxiliaryBasis.nativeModes,2), nModes+1);
    end

    candidateModeNumber = auxiliaryBasis.modeNumber(1:nModes);
    referenceEigenvalues = self.eigenvalues(1:nModes);
    candidateEigenvalues = auxiliaryBasis.eigenvalues(1:nModes);
    eigenvalueScale = max(1,max(abs([referenceEigenvalues candidateEigenvalues]),[],"all"));
    if ~isequal(candidateModeNumber,self.modeNumber(1:nModes)) ...
            || any(abs(candidateEigenvalues-referenceEigenvalues) > 1e-8*eigenvalueScale)
        error("IMBasisSet:AuxiliaryModeMismatch", ...
            "The auxiliary solve did not reproduce the retained mode prefix used by this basis set.");
    end
    generatingMode = auxiliaryBasis.nativeModes(:,nModes+1);
end

zRoots = self.solver.rootsOfNativeMode(generatingMode);
zTolerance = max(100*eps(max(1,max(abs(self.zDomain)))), 1e-10*max(1,diff(self.zDomain)));
zRoots = sort(zRoots(:));
zRoots = zRoots(zRoots > self.zDomain(1)+zTolerance & zRoots < self.zDomain(2)-zTolerance);
if ~isempty(zRoots)
    zRoots = zRoots([true; diff(zRoots) > zTolerance]);
end
z = [self.zDomain(1); zRoots; self.zDomain(2)];
if length(z) < nModes
    error("IMBasisSet:InsufficientQuadraturePoints", ...
        "The auxiliary mode produced %d full-depth points for %d retained modes.", length(z), nModes);
end
end
